[package]
name = "s3store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "S3-backed piece store"
publish = false

[dependencies]
aws-sdk-s3.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
hyper-util = { version = "0.1", features = ["server-auto", "tokio"] }
s3s = "0.12"
s3s-fs = "0.12"

[lints]
workspace = true
